### ISSUE TITLE
chaoss metrics meta-issue

### ISSUE THREAD

**Issue by mpadge** [ropensci-review-tools/repometrics#3]
https://chaoss.community/kb-metrics-and-metrics-models/ to be addressed through separate issues for each metric or model

## TODO

- [x] development responsiveness #4
- [x]  project engagement #5 
- [x] project awareness #6
- [x] community activity #7
- [x] OSS compliance and security #8
- [x] OSS Project Viability community #9
- [x] OSS Project Viability Starter #10
- [x] OSS Project Viability: Governance #15
- [x] OSS Project Viability: Strategy #16
- [x] Collaboration Development Index #11
- [x] Community Service and Support #12
- [x] Starter Project Health Metrics Model #13
- [x] Community Welcomingness #14

Those are all the models except for:
- [DEI Event Badging](https://chaoss.community/kb/metrics-model-dei-event-badging/)
- [Safety](https://chaoss.community/kb/metrics-model-safety/)
- [Funding](https://chaoss.community/kb/metrics-model-funding/)
- [Business Readiness of an Open Source Project](https://chaoss.community/kb/metrics-model-business-readiness-of-an-open-source-project/)

Each model includes numerous metrics, with individual metrics overlapping across different models. Once the individual metrics have been addressed, the model construction and interpretation can begin.

**Comment by mpadge** [comment]
These are now all done. A similar issue will now be opened to combine metrics into the distinct models listed above within the dashboard outputs.

**Comment by mpadge** [comment]
Just going to re-open this same issue to convert all of these into single "cm-models" outputs, using repeat of same checklist:

- [ ] development responsiveness #4
- [ ]  project engagement #5 
- [ ] project awareness #6
- [ ] community activity #7
- [ ] OSS compliance and security #8
- [ ] OSS Project Viability community #9
- [ ] OSS Project Viability Starter #10
- [ ] OSS Project Viability: Governance #15
- [ ] OSS Project Viability: Strategy #16
- [ ] Collaboration Development Index #11
- [ ] Community Service and Support #12
- [ ] Starter Project Health Metrics Model #13
- [ ] Community Welcomingness #14
